# Generated by Django 5.0.4 on 2024-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageObject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.SlugField(max_length=255),
        ),
    ]
