# Generated by Django 5.0.4 on 2024-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageObject', '0002_list_slug_alter_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
