# Generated by Django 5.0.4 on 2024-05-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageObject', '0003_alter_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
